Repository ucsb-cs156-w24/proj-gauchoride-w24-7pm-2, pull requests merged in 2024-03, with the labels that each got.

#33 Andy driver availability
  frontend/src/fixtures/driverAvailabilityFixtures.js
  src/main/java/edu/ucsb/cs156/gauchoride/entities/DriverAvailability.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/DriverAvailabilityRepository.java
Labels: 10, Merge Candidate

#35 ln - fixed "Apply to be a Rider" in NavBar and fixed ROLE_RIDER granted authority
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptor.java
  src/test/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptorTests.java
Labels: 5, Merge Candidate

#40 Andy ride request field names
  frontend/src/main/components/Ride/RideForm.js
  frontend/src/main/components/Ride/RideTable.js
  frontend/src/tests/components/Ride/RideForm.test.js
  frontend/src/tests/components/Ride/RideTable.test.js
Labels: 10, Merge Candidate

#41 Andy field names hover (optional part from issue #94)
  frontend/src/main/components/Ride/RideForm.js
  frontend/src/tests/components/Ride/RideForm.test.js
Labels: 5, Merge Candidate

#43 eh - DriverAvailabilityForm + tests + stories
  frontend/src/main/components/Driver/DriverAvailabilityForm.js
  frontend/src/stories/components/Driver/DriverAvailabilityForm.stories.js
  frontend/src/tests/components/Driver/DriverAvailabilityForm.test.js
Labels: 10

#45 eh - fixed Driver Dashboard typo in nav bar
  frontend/src/main/components/Nav/AppNavbar.js
Labels: 5, Merge Candidate

#34 KV - DriverAvailibilityTable, DriverAvailibilityUtils
  frontend/src/main/components/Driver/DriverAvailabilityTable.js
  frontend/src/main/components/OurTable.js
  frontend/src/main/utils/driverAvailibilityUtils.js
  frontend/src/stories/components/Driver/DriverAvailibilityTable.stories.js
  frontend/src/tests/components/Driver/DriverAvailabilityTable.test.js
  frontend/src/tests/utils/driverAvailibilityUtils.test.js
Labels: 15

#44 AW - Driver Availability Controller
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: 15

#46 ln - Rider Application Admin Pages
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/RiderApplication/RiderApplicationForm.js
  frontend/src/main/components/RiderApplication/RiderApplicationTable.js
  frontend/src/main/pages/RiderApplication/RiderApplicationEditPageMember.js
  frontend/src/main/pages/RiderApplication/RiderApplicationIndexPageAdmin.js
  frontend/src/main/pages/RiderApplication/RiderApplicationReviewPageAdmin.js
  frontend/src/main/pages/RiderApplication/RiderApplicationShowPageMember.js
  frontend/src/stories/pages/RiderApplication/RiderApplicationIndexPageAdmin.stories.js
  frontend/src/stories/pages/RiderApplication/RiderApplicationReviewPageAdmin.stories.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationIndexPageAdmin.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationReviewPageAdmin.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationShowPage.test.js
Labels: Merge Candidate

#42 Mw - rider application "show" page
  frontend/src/stories/components/RiderApplication/RiderApplicationShowPageMember.stories.js
Labels: 10, Merge Candidate

#49 AW - DriverAvailability Pages + Stories
  frontend/src/App.js
  frontend/src/main/components/Driver/DriverAvailabilityForm.js
  frontend/src/main/components/Driver/DriverAvailabilityTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Drivers/DriverAvailabilityCreatePage.js
  frontend/src/main/pages/Drivers/DriverAvailabilityEditPage.js
  frontend/src/main/pages/Drivers/DriverAvailabilityIndexPage.js
  frontend/src/stories/pages/Driver/DriverAvailabilityCreatePage.stories.js
  frontend/src/stories/pages/Driver/DriverAvailabilityEditPage.stories.js
  frontend/src/stories/pages/Driver/DriverAvailabilityIndexPage.stories.js
  frontend/src/tests/components/Driver/DriverAvailabilityForm.test.js
  frontend/src/tests/components/Driver/DriverAvailabilityTable.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityEditPage.test.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityIndexPage.test.js
  frontend/src/tests/pages/Drivers/DriverAvailabiltyCreatePage.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
Labels: 20
